### ISSUE TITLE
Skriva första blogginlägget för nylansering

### ISSUE THREAD

**Issue by mattiasaxell** [okfse/opengovse#1]
T.ex. beskriva kort om vad, varför hur etc?
En bloggpost som kanske kan ha en vinkel som verkar mot samma effekt vi försöker uppnå med sajten?
Vi får bolla kring denna.

**Comment by mattiasaxell** [comment]
@peterk Vill du att jag knappar vidare på ett första blogginlägg som du kan skriva vidare på / ge feedback på?

**Comment by peterk** [comment]
Jag tog din text och knappade vidare på en del saker. Känns den ok? Antingen är det ett inlägg eller så får det ligga statiskt på startsidan under en tid ovanför nyheter?

**Comment by mattiasaxell** [comment]
Ja det ser bra ut! Ändrade lite jag också. Tänker att den kan ligga kvar ett tag som du föreslår. Senare kan vi lägga till en /om-sida där vi kan lägga in den när det finns fler nyheter. Då kan vi också lägga in stödjande aktörer av olika slag. Hur låter det?

**Comment by mattiasaxell** [comment]
Lade in /om-sida där jag remixade lite från första bloggposten och footer.html. Tycker det ser rätt klart ut! :)
