### ISSUE TITLE
Add Myndigheterna.se - as easy info portal to authorities

### ISSUE THREAD

**Issue by mattiasaxell** [okfse/opengovse#17]
@peterk we could also add this http://myndigheterna.se as an information portal to authorities.

**Comment by peterk** [comment]
Låter som ett case.

**Comment by mattiasaxell** [comment]
@peterk Sant! Jag har gjort ett litet hack med rådata från SKL och SCB som kommer upp som .csv på http://publicbodies.org/ - kan skriva om det också som premiär-case.

**Comment by mattiasaxell** [comment]
Stänger p.g.a. stängd site.
