### ISSUE TITLE
Lnkar fungerar ej

### ISSUE THREAD

**Issue by salgo60** [okfse/opengovse#20]
Se http://www.opengov.se/lardigmer.html

![image](https://user-images.githubusercontent.com/14206509/43774994-6000ef58-9a4b-11e8-87a8-ff138d3a3967.png)

**Comment by mattiasaxell** [comment]
Tack för observationen och ping @salgo60 - tråkigt att public service tar bort utbildande klipp om offentlighetsprincipen. Jag kollar med SVT om de kan lägga upp klippet och kompletterande klipp med Anders R. Olsson igen.

**Comment by salgo60** [comment]
Tror rent allmänt det behövs en större mognad. Jag håller på en del med Wikidata och semantisk web och det är galet med länkröta eller myndigheter inte har koll / har bra ändringshantering 

- Projekt att koppla ihop lite kulturarv [wmse-riksarkivet-tora](https://phabricator.wikimedia.org/tag/wmse-riksarkivet-tora/)
- [städprojekt](http://salgo60.github.io/Svenskaforsamlingar)  
- [DIGG issues](https://github.com/salgo60/DIGG-skuggbacklog/issues?q=is%3Aissue+l%C3%A4nkr%C3%B6ta+) med länkröta

**Comment by mattiasaxell** [comment]
Ja verkligen. Kan tänka mig att det är länkröta, stöter ofta på det. Återkommer när jag får någon återkoppling från SVT.

**Comment by mattiasaxell** [comment]
Väntar på svar och har rensat bort länkar jag såg kunde tas bort.
