### ISSUE TITLE
Fixa innehåll till lardigmer.html 

### ISSUE THREAD

**Issue by mattiasaxell** [okfse/opengovse#5]
Lägg till grundläggande info för att lära sig mer om OpenGov-rörelsen och filosofi.

**Comment by mattiasaxell** [comment]
@peterk Vad ska vi ha bland intromaterial? Om du specar önskemål kan jag börja fixa direkt.

**Comment by peterk** [comment]
Kan det vara något i stil med detta? http://www.europeandataportal.eu/en/content/training-library

Eller bara länkar till opendatahandbook m.fl.?

**Comment by mattiasaxell** [comment]
Jättebra! Lägger in såna typer av material!
