### ISSUE TITLE
Gör till Project Page för CNAME custom domain

### ISSUE THREAD

**Issue by mattiasaxell** [okfse/opengovse#7]
Bra guide:
http://www.thinkful.com/learn/a-guide-to-using-github-pages

opengovse-situation >>> http://www.thinkful.com/learn/a-guide-to-using-github-pages/start/existing-project/project-page/existing-repo/

**Comment by peterk** [comment]
Den där guiden visar väl bara hur man kommer igång med vanliga github pages? Vi har redan det uppsatt. Frågan är om man kan få ett CNAME till en sajt som ligger i en underkatalog på ett smidigt sätt men det verkar krångligt. Vi vill ju inte att opengovsajten blockerar okfse om den ska ha något annat framöver heller. Ett alternativ är att vi deployar sajten på en vanlig server med jekyll från detta repo istället för att vara beroende av github pages. Det möjliggör även https. Ska kika på det.

**Comment by mattiasaxell** [comment]
OK. Jag förstår det som att GitHub-guiden¹ förklarar att det ska gå. Har som sagt själv tragglat med det. Ja det låter som ett bra alternativ. Ytterligare ett alternativ är att skapa en opengovse-organisation här som kan göra det mer intressant för fler organisationer att samlas kring det. Vad tror du om det?

Tycker att denna guide² och denna³ inte hjälper särskilt mkt kring hur man får project page att rulla med custom domain.

¹ https://help.github.com/articles/user-organization-and-project-pages/#project-pages
² https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/
³ https://help.github.com/articles/adding-a-cname-file-to-your-repository/

**Comment by peterk** [comment]
Ah, det verkar som att man helt enkelt inte kan få till det med githubs projektsidor så att det lirar på ett bra sätt. Man kan få en underdomän typ opengov.opengov.se men det blir ju konstigt. Custom hosting då kanske.

**Comment by mattiasaxell** [comment]
Jag förstår det som att det ska fungera när jag läser detta: "_Project Pages sites that use a custom domain are also available at username.github.io/projectname for personal accounts, and orgname.github.io/projectname for organizations._" Tänker att det borde funka. Vilket alternativ föredrar du?
1.Testa lägga CNAME här och peka om opengov.se hit? Ser att du testar custom domain nu, den verkar inte ha dirigerats om ännu. Det kanske värt att höra av sig till support på Github för att få det att lira här?
2. Starta en opengovse-organisation på Github?
3. Custom hosting?

**Comment by peterk** [comment]
Antingen får man www.opengov.se/ [projektnamn] eller [projektnamn].opengov.se vilket kanske inte blir så snyggt. Jag har skapat denna nu: http://beta.opengov.se/ och det verkar lira. Jag kan bygga om sajten från repot med ett kommando manuellt. Får vi till flödet där så kanske vi kan köra på den modellen. Filerna hamnar på en annan server. Då kan github pages sidan bli ett slags stagingmiljö där man kan kolla in att saker blir rätt innan man deployar dem till sajten.

**Comment by mattiasaxell** [comment]
http://www.opengov.se kan fungera även om det kanske är lite old school vid det här laget! Kanske går att leka med någon slags kreativt subdomän-hack som go./join./hello.opengov.se för att bygga vidare på de effektmål vi önskar. :smile_cat: Snyggt att du fick till beta.opengov.se!

Det låter också som en sund variant! Vi kanske kan testa oss fram och börja med beta.opengov.se? :)

**Comment by peterk** [comment]
Så fort vi har lite mer intro material tänker jag att vi deployar om den till www.opengov.se

**Comment by mattiasaxell** [comment]
Ok, perfekt. Kan jobba på det nu.

**Comment by mattiasaxell** [comment]
Har lagt upp rapporter &  case-sida där besökaren uppmanas tipsa om bra case i Sverige. Kan du deploya om domänen till www.opengov.se på Sön 27/12 så kan vi köra ut på sociala medier? :)

**Comment by peterk** [comment]
Med de senaste teaksen kanske det är läge att gå live? Kan du kolla igenom beta.opengov.se och kolla om det verkar ok?

**Comment by mattiasaxell** [comment]
@peterk Ja det tycker jag verkligen. Jag tycker det ser bra ut. Ser inte Twitter-widgeten, men den fungerar säkert, jag kör blockers som skalar bort den. Kan lägga till att vi har fått fina ord om revisionen innan idag så med dina förbättringar idag är det ännu mer redo!

**Comment by mattiasaxell** [comment]
@peterk Hojta till när det är klart så kan vi skicka ut lite komm om det.

**Comment by peterk** [comment]
DNS ändrad. Stänger denna när vi ser att det slagit igenom.

**Comment by mattiasaxell** [comment]
Stänger pga lyckad DNS-ändring. Finns ny push att göra till webbserver. :smile_cat:
