### ISSUE TITLE
Högerkolumn index.html

### ISSUE THREAD

**Issue by mattiasaxell** [okfse/opengovse#9]
@peterk Tänkte att högerkolumnen på framsidan kunde vara snabblänkar till #opengov-hashtag och bloggar kring ämnet. Har lagt in lite content där. Kom gärna med förslag och feedback hur den grejen kan bli bättre.

**Comment by peterk** [comment]
Jag testade att lägga in twitterflödet där nu och flyttade ner länkarna till vänstersidan. Jämnade ut layouten lite. Vad tror du?

**Comment by mattiasaxell** [comment]
Det ser bra ut! :smile: +1
